### ISSUE TITLE
Call Rect not flat?

### ISSUE THREAD

**Issue by callimero** [mrossini-ethz/camera-calibration-pvr#1]
Hi,

after not moving or scaling the initial plane in OBJECT Mode, I got the Calrect to match in Camera View. However it is not flat X-Y? What did I wrong? Did I missunderstand the purpose of the plugin?

**Comment by mrossini-ethz** [comment]
Hi callimero

Thank you for trying the add-on.

Let me make sure that I understand you correctly: You created a plane mesh and moved the vertices to the corners of the rectangle in the image from top view. You did this without moving or scaling the object itself (which should not matter). Let's say this mesh is called 'Plane'. After leaving edit mode, you pressed the 'Camera Calibration' button. This caused a new object called 'CalRect' to be created.

CalRect should be almost completely flat in the x-y. Almost, but not completely. If this is not so, then I can think of one (very technical) reason why. It has never occurred when I tried it.

Is it possible that you post the console output when you press 'Camera Calibration'? On Windows you would have to go to Help -> Toggle System Console. On Linux or Mac you would have to start blender from a terminal and look at the terminal output. It would be extremely helpful as well, if you could attach your .blend file with the situation **just before** (!) pressing 'Camera Calibration'.

I am looking forward to fixing all bugs that we may find.

**Comment by callimero** [comment]
I tried with this image and the result was ok'ish (extruded the plane but the perpective did not quite match with the house).

http://img.fotocommunity.com/hochhaus-am-rhein-rotterdam-c4ffeea3-01c7-485a-a692-af53d7b4241b.jpg?height=1080

Console:

<Vector (0.0000, 0.0000, 0.0000)>
Vertices: <Vector (-0.9862, -1.5745)> <Vector (0.9100, -1.5565)> <Vector (0.9169
, 1.4361)> <Vector (-0.8504, 1.1017)>
ld: 1.0636412175363157
Angles:
89.99997518372149
89.99988639126228
90.00002982523485
90.00011178750489
Result:
Focal length: 28.644351997683373
Camera Rx: 14.266584459747998
Camera Ry: 30.036472419020107
Camera Rz: 1.713584941757804
Camera x: 0.47828221321105957
Camera y: -0.21177762746810913
Camera z: 0.8042410612106323
Rectangle length: 0.2265948338548199
Rectangle width: 0.3101383059947876
Rectangle A: <Vector (-0.1133, -0.1551, -0.0000)>
Rectangle B: <Vector (0.1133, -0.1551, 0.0000)>
Rectangle C: <Vector (0.1133, 0.1551, -0.0000)>
Rectangle D: <Vector (-0.1133, 0.1551, 0.0000)>


But when I try with an own image (maybe shot from a strange perspective) I get nonsense. One Angle is not quite 90°...

<Vector (0.0000, 0.0000, 0.0000)>
Vertices: <Vector (-1.6959, -0.6878)> <Vector (2.9007, -0.7654)> <Vector (2.7606
, 1.7254)> <Vector (-1.5671, 2.0824)>
ld: 0.8885866047217561
Angles:
90.00000250447816
92.42866067898379
77.85358340531018
90.00000250447816
Result:
Focal length: 21.719531235949248
Camera Rx: -4.835518053779612
Camera Ry: -22.83627477998716
Camera Rz: 0.7528525709616795
Camera x: -0.5385738611221313
Camera y: -0.004370242357254028
Camera z: 0.9142982959747314
Rectangle length: 0.7568295226286703
Rectangle width: 0.3809437642993558
Rectangle A: <Vector (-0.3884, -0.1813, -0.0584)>
Rectangle B: <Vector (0.3584, -0.2189, 0.0584)>
Rectangle C: <Vector (0.4184, 0.2189, -0.0584)>
Rectangle D: <Vector (-0.3884, 0.1813, 0.0584)>

[beforeHaus.zip](https://github.com/mrossini-ethz/camera-calibration-pvr/files/718974/beforeHaus.zip)

HTH!
Carsten

**Comment by mrossini-ethz** [comment]
Hi Carsten

Thank you very much for the information!

First off, the building in the image hochhaus-am-rhein does not seem to be a built using right angles! If you look closely, you will see that the wall facing the viewer leans back slightly (modern architecture!). This is why the building does not match the cube that you get when extruding the rectangle. Do you agree? In this case, there is no issue with the add-on.

Now the zip file that you attached is very interesting. My initial suspicion turns out to be correct. The algorithm was using the wrong solution. Thank you for finding this bug! I will correct it as soon as possible.

Bug confirmed!

**Comment by callimero** [comment]
Glad I could help. I tested some more images and it seems to be hard to find architecture images which are not somehow tilt-shifted or other wise processed. I also think that if the selected face is quite in the XY plane the solution fails more often? I mean that would make sense (to me, but I suck at math) there is less information then...

**Comment by mrossini-ethz** [comment]
As I said: modern architecture (sigh). Usually _one_ angle is perpendicular. In the case of hochhaus-am-rhein, the roof and the wall facing the viewer are _not_ 90 degrees. The two visible walls, however, seem to be. Therefore, you can calibrate the wall facing the viewer and then extrude, but then move the vertices along another axis to match the geometry in the image. You should get good results that way.

Edit: Ah, yes tilt-shifting. And cropping. This moves the optical centre away  from the image centre. This will make the add-on fail. I will need to point this out in the documentation.

**Comment by mrossini-ethz** [comment]
The problem should now be fixed. Can you confirm?

**Comment by callimero** [comment]
Yes, with my house it produces now usable solutions. I think not perfect, but that may be because of the lens distorsion or that I did not set the points optimally.
