### ISSUE TITLE
The add-on can't register in Blender 2.79

### ISSUE THREAD

**Issue by Ribel78** [mrossini-ethz/camera-calibration-pvr#4]
The add-on can't register in Blender 2.79 after installing from the zip file.
Manually activating the py file brings the following error:
Traceback (most recent call last):
  File "\camera-calibration-pvr.py", line 945, in module
  File "\camera-calibration-pvr.py", line 939, in register
  File "\camera-calibration-pvr.py", line 913, in update_panel
KeyError: 'bpy_prop_collection[key]: key "__main__" not found'

**Comment by mrossini-ethz** [comment]
Hi Ribel78 and thank you for your report. Which operating system are you running on? I will try to check this on my linux machine over the weekend.

**Comment by mrossini-ethz** [comment]
Hi Ribel78

I have tried this and found that when I go to File -> User Preferences -> Install Addon From File and then select the zip file that I download from GitHub, then there is no problem. However, if I unzip the zip file and then load the camera-calibration-pvr.py file in the Blender Text Editor and then push on "Run Script", the error that you describe occurs. (However, it says it's the key "__main__" in my case, not just "main".)

I think it is fixed now. I pushed the change into a new "devel" branch here on GitHub ([zip](https://github.com/mrossini-ethz/camera-calibration-pvr/archive/devel.zip)). Can you please check it out?

**Comment by brothermechanic** [comment]
my error for last devel version (may be same)

```
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 350, in enable
    mod.register()
  File "/home/bm/.config/blender/2.79/scripts/addons/camera-calibration-pvr.py", line 947, in register
    update_panel(None, bpy.context)
  File "/home/bm/.config/blender/2.79/scripts/addons/camera-calibration-pvr.py", line 913, in update_panel
    CameraCalibrationPanel.bl_category = context.user_preferences.addons["camera-calibration-pvr"].preferences.category
AttributeError: 'NoneType' object has no attribute 'category'
```
ps: in stable master all is ok.
Thank you for this script!

**Comment by mrossini-ethz** [comment]
Thank you, I will look into it.

**Comment by schroef** [comment]
Should that be update_panel(self, bpy.context)?

Not sure why you update the panel from the register part, just call the function in the beginning is the same, i think :)

The panel will update always the first time its loaded or when blender loads or when scene is loaded

**Comment by mrossini-ethz** [comment]
I tried to fix it. Can you try again with the latest commit on the "devel" branch?

schroef: I don't know. That was your code ;-)

**Comment by brothermechanic** [comment]
Hello
I just test last version from devel branch
https://i.imgur.com/OzBFjzT.jpg
Now it's works great for me!
Witch one better to use with latest blender from git master? Your master or devel version? 
Now works both of them without bugs.

**Comment by brothermechanic** [comment]
Thank you for this addon!
It's much easy than blam!

**Comment by mrossini-ethz** [comment]
Are you saying that both devel and master are working now? How can that be?

**Comment by brothermechanic** [comment]
Yes)
I don't know why)))
I double check it now, all 2 scripts working (may be only in my case)
(my system is gentoo amd64 gcc-7.2 python-3.6.3)
Witch one is better?

**Comment by mrossini-ethz** [comment]
Are you sure that you are actually changing scripts? Could it be that you are accidentally using only the devel version?

**Comment by brothermechanic** [comment]
I'm sure
i check it double

**Comment by schroef** [comment]
perhaps add self where it says one. I dont have 2.79 yet.

I use different render engine, this version causes soms sort off lagg. so I
reverted to 2.78c
